version: '3.4'

services:
  slackjukebox:
    image: slackjukebox
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    env_file:
      .env
    ports:
      - 3000:3000
      - 9229:9229
    cap_add:
      - SYS_ADMIN
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]