version: '3.4'

services:
  slackjukebox:
    image: rafaheringer/slack-jukebox
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file:
      .env
    ports:
      - 3000:3000
    cap_add:
      - SYS_ADMIN